de-mae-para-mae/config/routes.rb
Rails.application.routes.draw do
	resources :maes
	resources :anuncios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

de-mae-para-mae/app/models/anuncio.rb
class Anuncio < ApplicationRecord
  belongs_to :mae
end

de-mae-para-mae/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

de-mae-para-mae/app/models/mae.rb
class Mae < ApplicationRecord
end

de-mae-para-mae/app/controllers/anuncios_controller.rb
class AnunciosController < ApplicationController
	def new 
		@anuncio = Anuncio.new
		@maes = Mae.all
	end

	def create 
        @mae=Mae.find_by nome: params[:mae]
		@anuncio = Anuncio.new(params.require(:anuncio).permit(:titulo,:tipo,:idade_minima,:idade_maxima,:descricao))
		@anuncio.mae=@mae
		@anuncio.save
		redirect_to @anuncio
	end

	def index
		@anuncios=Anuncio.all
	end
end

de-mae-para-mae/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

de-mae-para-mae/app/controllers/maes_controller.rb
class MaesController < ApplicationController
	def new
		
	end

	def create
		@mae = Mae.new(params.require(:mae).permit(:nome, :email, :telefone, :cidade, :estado) )

		@mae.save 
		redirect_to :controller => 'anuncios', :action => 'new'

		

		
	end
	
	def show
	end
end

de-mae-para-mae/app/helpers/anuncio_helper.rb
module AnuncioHelper
end

de-mae-para-mae/app/helpers/application_helper.rb
module ApplicationHelper
end

de-mae-para-mae/app/helpers/mae_helper.rb
module MaeHelper
end

de-mae-para-mae/app/views/anuncios/index.html.erb
<h1>Anúncios disponíveis</h1>


<table>
	
	<tr>
<th>Mãe</th>
<th>Titulo</th>
<th>Cidade</th>
<th>Estado</th>
	</tr>

	<% @anuncios.each do |anuncio| %>
	<tr>
		<td><%= anuncio.mae.nome %></td>
		<td><%= anuncio.titulo %></td>
		<td><%= anuncio.cidade %></td>
		<td><%= anuncio.estado %></td>

	</tr>
	<% end %>

</table>

de-mae-para-mae/app/views/anuncios/new.html.erb
<h1>Cadastro de anúncio</h1>
<%= form_for :anuncio, url: anuncios_path do |f| %>
	<p>
		<%= f.label :mae %><br>
		<%= f.select :mae, collection: @maes.map(&:nome) %>
	</p>
	<p>
		<%= f.label :titulo %><br>
		<%= f.text_field :titulo %>
	</p>
<p>
		<%= f.label :tipo %><br>
		<%= f.text_field :tipo %>
	</p>
	<p>
		<%= f.label :idade_minima %><br>
		<%= f.number_field :idade_minima %>
	</p>
	<p>
		<%= f.label :idade_maxima %><br>
		<%= f.number_field :idade_maxima %>
	</p>
	<p>
		<%= f.label :descricao %><br>
		<%= f.text_area :descricao %>
	</p>
<p>
		<%= f.submit "Crie agora!" %>
	</p>





<% end %>

de-mae-para-mae/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeMaeParaMae</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

de-mae-para-mae/app/views/maes/new.html.erb
<h1>Cadastro de mãe</h1>
<%= form_for :mae, url: maes_path do |f| %>
	<p>
		<%= f.label :nome %><br>
		<%= f.text_field :nome %>
	</p>


	<p>
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</p>

	<p>
		<%= f.label :telefone %><br>
		<%= f.text_field :telefone %>
	</p>

	<p>
		<%= f.label :cidade %><br>
		<%= f.text_field :cidade %>
	</p>

	<p>
		<%= f.label :estado %><br>
		<%= f.text_field :estado %>
	</p>


	<p>
	<%= f.submit "Vamos lá!" %>
	</p>









<% end %> 